apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-api
  template:
    metadata:
      labels:
        app: ingestion-api
    spec:
      containers:
        - name: ingestion-api
          image: hook-observer-api:latest
          imagePullPolicy: Never # Use local image from minikube/kind
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgres://user:password@postgres:5432/hookdb?sslmode=disable"
            - name: KAFKA_BROKER
              value: "kafka:9092"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-api
spec:
  type: ClusterIP
  selector:
    app: ingestion-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ingestion-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingestion-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
